info:
  name: §a§l[UCR]§r
  pl: false
stock: 0
hit:
  1:
    1:
      1: 1のゾロ目
    2:
      3: まんじゅう
  2:
    2:
      2: 2のゾロ目
  3:
    3:
      3: 3のゾロ目
    2:
      1: まんじゅう？
  4:
    4:
      4: 4のゾロ目
  5:
    5:
      5: 5のゾロ目
  6:
    6:
      6: out